apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqldatabases.database.example.com
spec:
  group: database.example.com
  names:
    kind: XPostgreSQLDatabase
    plural: xpostgresqldatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  size:
                    type: string
                    description: Database size (small, medium, large)
                    enum:
                    - small
                    - medium
                    - large
                    default: small
                  storageGB:
                    type: integer
                    description: Storage size in GB
                    minimum: 20
                    maximum: 1000
                    default: 20
                  version:
                    type: string
                    description: PostgreSQL version
                    enum:
                    - "14"
                    - "15"
                    - "16"
                    default: "15"
                  location:
                    type: string
                    description: Azure region
                    default: eastus
                required:
                - storageGB
            required:
            - parameters
          status:
            type: object
            properties:
              ready:
                type: boolean
              endpoint:
                type: string
              backupLocation:
                type: string
